spring.application.name=Workout App

spring.datasource.url=jdbc:postgresql://localhost:5432/workout-db
spring.datasource.username=postgres
spring.datasource.password=Vanan@191093
spring.datasource.driver-class-name=org.postgresql.Driver